Add droidcon-london-2023
AndroidStudyGroup/conferences pull request #755
Opened 2023-02-21 19:02 UTC by ivangarzab

2023-02-21 21:17 UTC, cketti requested changes
For consistency please rename the file to `droidcon-uk-2023.md`

2023-02-21 23:53 UTC, ivangarzab commented
> For consistency please rename the file to `droidcon-uk-2023.md`

No problem!

2023-02-22 00:00 UTC, cortinico approved these changes

2023-02-22 09:56 UTC, cketti approved these changes

2023-02-22 09:57 UTC, merged

2023-02-22 09:57 UTC, cketti commented
Thanks :+1: